### ISSUE TITLE
Allow docker resources from different folders

### ISSUE THREAD

**Issue by rcannood** [data-intuitive/viash#40]
Docker doesn't allow resources from different folders. Example:

```yaml
setup:
  - type: docker
    resources: 
      - resource.txt some/resource.txt
```

Behind the screens, viash could create a workaround for this.
